# Generated by Django 5.2.1 on 2025-05-19 18:00

import django.core.validators
import django.db.models.deletion
import django_mongodb_backend.fields
import parking.models
import paying.models
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создание')),
                ('start', models.DateTimeField(validators=[django.core.validators.MinValueValidator(paying.models.min_start, 'Введите время не раньше текущего, чем на 5 минут')], verbose_name='Начало')),
                ('end', models.DateTimeField(verbose_name='Конец')),
                ('duration', models.DurationField(verbose_name='Длительность')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('parking_detail', django_mongodb_backend.fields.EmbeddedModelField(embedded_model=parking.models.EmbeddedParking, verbose_name='Данные о парковке')),
                ('user_detail', django_mongodb_backend.fields.EmbeddedModelField(embedded_model=users.models.EmbeddedUser, verbose_name='Данные о пользователе')),
                ('parking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='parking.parking', verbose_name='Парковка')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
    ]
