# Generated by Django 5.2.1 on 2025-05-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paying', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='start',
            field=models.DateTimeField(verbose_name='Начало'),
        ),
    ]
