# Generated by Django 5.2.1 on 2025-05-19 18:00

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('third_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Статус персонала')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее редактирование')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Регистрация')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='EmbeddedUser',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('third_name', models.CharField(max_length=30, null=True, verbose_name='Отчество')),
                ('created_at', models.DateField(verbose_name='Регистрация')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Статус персонала')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
