# Generated by Django 5.2.1 on 2025-05-19 18:00

import django.core.validators
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddedParking',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_zone', models.PositiveIntegerField(verbose_name='Зона парковки')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('total_lots', models.PositiveIntegerField(verbose_name='Всего мест')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за час')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_zone', models.PositiveIntegerField(verbose_name='Зона парковки')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('total_lots', models.PositiveIntegerField(verbose_name='Всего мест')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за час')),
            ],
            options={
                'verbose_name': 'парковка',
                'verbose_name_plural': 'Парковки',
            },
        ),
    ]
